### PR TITLE
Grammar and formatting.

### PR DESCRIPTION
**Pull request by bendiy**

### CODE REVIEW

**Comment by JerrySievert** [comment]
I'll resolve these conflicts, don't worry about it.

**Comment by bendiy** [comment]
@JerrySievert I removed the `Remote debugger` references. Should be able to merge now.

**Comment by bendiy** [comment]
@JerrySievert Can you merge this? I'd like to get the docs on here fixed and I don't know if this is enough:
https://pgxn.org/dist/plv8/doc/plv8.html

#216

**Comment by JerrySievert** [comment]
yeah, been waiting to cut another release, this is a good time.

thanks for the reminder.

there are a few other changes I'll want to make for the release as well.  as awesome as pgxn is, not being able to overwrite a release is sometimes difficult.

**Pull request merged**
