### PR TITLE
Add JSONB Support

### PR DESCRIPTION
**Pull request by JerrySievert**
This adds `JSONB` support to PLV8 for pg versions 9.4.x and above.

Unfortunately, `CStringGetJsonb` does not currently exist in jsonb.c, so this works around it by making a direct function call via `DirectFunctionCall1`.

`CStringGetJsonb` should be added to Postgres core, at which point this implementation should be changed to use it.

### CODE REVIEW

**Comment by JerrySievert** [comment]
a good test function:

```sql
CREATE OR REPLACE FUNCTION test2(data jsonb) RETURNS
JSONB AS $$
  return data;
$$ LANGUAGE plv8 IMMUTABLE STRICT;
```

**Comment by schwebke** [comment]
+1

Note: This PR and https://github.com/plv8/plv8/pull/115 together would result in a merge conflict, as #115 already contained partial jsonb support. I propose https://github.com/schwebke/plv8/commit/abf16672c3ef1849a93053bbda3b9ac04391f555 to resolve it.

**Comment by JerrySievert** [comment]
if you want to cherrypick, go ahead - the pain was doing the research to get back into jsonb (the part you are missing).

**Comment by JerrySievert** [comment]
as soon as @schwebke adds the jsonb support, i will close this in deference.  the new plv8 changes should be merged ASAP regardless.  is there anything anyone can do to help encourage this?

**Comment by schwebke** [comment]
@JerrySievert: I merged these changes into #115 as proposed.

**Comment by JerrySievert** [comment]
Great, going to close in deference to #115

**Comment by rafaelveloso** [comment]
Great, thanks!

**Pull request closed without merging**
