### PR TITLE
fix resource owner and context

### PR DESCRIPTION
**Pull request by JerrySievert**
this fixes resource owner issues and context issues.

much better fix moving forward.

### CODE REVIEW

**Comment by JerrySievert** [comment]
@ruimarinho this should fix any issues moving forward.  about to close my day, will try to work on other issues tomorrow.

**Comment by ruimarinho** [comment]
Interesting - my experience with resource owner crashes are not using plv8.execute/plv8.subtransaction. I'll test this patch.

**Comment by JerrySievert** [comment]
i think this is a a nascent issue, and may not be as exposed due to garbage collection.

there's no reason why it shouldn't be changed regardless

**Comment by ruimarinho** [comment]
I have just confirmed the resource owner issue still exists on v1.5.2.

**Comment by ruimarinho** [comment]
Also confirmed as not fixed on v1.4.7.

**Comment by JerrySievert** [comment]
do you have a simple test case for this that we can add to regressions?

we have one simple regression already: https://github.com/plv8/plv8/blob/master/sql/currentresource.sql#L1-L9

**Comment by ruimarinho** [comment]
Not yet, but I can reproduce it and it's inside this query (where _ and assign come from the previously discussed memory context example issue):

```sql
UPDATE foos
SET bar = _.assign(bar, '{"prop":1}')
WHERE "id" = '7a19fee6-ed96-4ddd-bcc8-6916a30e2005'
```

**Comment by JerrySievert** [comment]
hm. the odd part of that is that _ isn't using a `plv8.execute`.

**Comment by ruimarinho** [comment]
I'm on this now.. do you have spare time for some debugging? I'm on irc (same handle as github's).

**Comment by JerrySievert** [comment]
that is awesome - unfortunately my tuesdays are always booked.  i can help tomorrow, though.

**Comment by ruimarinho** [comment]
No worries :) I'll try to join tomorrow then.

**Comment by JerrySievert** [comment]
as a heads up, i'm "jerrysv" on freenode (sv is the international symbol for "sievert"), and i'm online about 14 hours/day - feel free to message me, i am not always available (i'm in a ton of meetings), but can at least asynchronously reply!

**Comment by JerrySievert** [comment]
@christopherberg released 1.4.8, should be the last fix for this, i hope.

**Comment by ChristophBerg** [comment]
Debian packages built, thanks for the notice!

**Comment by JerrySievert** [comment]
thanks @ChristophBerg ! you rock!

**Comment by ruimarinho** [comment]
Confirmed as fixed on 1.4.8 and 1.5.3. Awesome work @JerrySievert!

**Pull request merged**
