### PR TITLE
Extend error object info

### PR DESCRIPTION
**Pull request by car3ca**
Error object extended to include postgresql error data.

### CODE REVIEW

**Comment by JerrySievert** [comment]
this looks good, and seems to be backward compatible!

**Comment by car3ca** [comment]
Great! Thank you!

**Comment by JerrySievert** [comment]
i'm trying to track down an OS X issue that occurs when this code is merged - do you have access to OS X?

**Comment by car3ca** [comment]
Yes, I currently have 10.8.5 installed. Can I help?

**Comment by JerrySievert** [comment]
can i talk you into re-submitting a pull request with this change?

**Comment by car3ca** [comment]
done! won't it revert everything afterwards?

**Comment by JerrySievert** [comment]
i'll try to pull in the changes via git cherry-pick

**Comment by car3ca** [comment]
ok, but how could i do what you asked? so i can help you next time.

**Comment by JerrySievert** [comment]
maybe by merging up to date, and applying the changes again.

i have it cherry-picked into a branch, just waiting to close a memory leak issue, then i'll get it right back in.

thanks!

**Comment by car3ca** [comment]
i created a new pull request https://github.com/plv8/plv8/pull/154.
not sure if this is what you wanted, but i hope it can help.

**Pull request merged**
