### PR TITLE
Fixes #268 - Move DirectFunctionCall1() and other logic into PG_TRY/PG_CATCH.

### LINKED ISSUE #268: Restore of a database that contains plv8 code fail when `plv8.start_proc` is set
If your `postgresql.conf` contains a `plv8.start_proc` setting such as:

```
plv8.start_proc = 'xt.js_init'
```

A database backup that contains plv8 code will fail to restore or at least throw a bunch of errors and not restore any of the plv8 parts. This happens because the database backup will try to execute `CREATE EXTENSION plv8;` when it restores, which will fail with the error:
`schema 'xt' does not exist`

If the `start_proc` is in the `public` schema, `plv8.start_proc = 'js_init'`, the error will be:
`function 'js_init' does not exist`

Those errors happen because the database is empty and none of that exists. Because the `plv8` extension is never created, none of the plv8 code in the backup will be added to the database on restore. A similar issue happens if you do run `CREATE EXTENSION plv8;` before the restore. The plv8 code will fail to restore because the `xt.js_init()` function doesn't exist yet. When the restore tries to create it, the error thrown in the `start_proc` checking code prevents it from being created.

This happens because [`DirectFunctionCall1(regprocin, CStringGetDatum(plv8_start_proc))`](https://github.com/plv8/plv8/blob/377216eea27bc1e6ba7d185e82ae20f12c61865b/plv8.cc#L1536) throws an error. If this call is wrapped in the `PG_TRY();/PG_CATCH();`, the error will be ignored, the extension gets created and the plv8 code in the backup is restored correctly.

A work around to this has been:
1. Comment out the `plv8.start_proc = 'xt.js_init'` line in `postgresql.conf`.
2. Restart PostgreSQL service.
3. Restore the backup.
4. Un-comment the `plv8.start_proc = 'xt.js_init'` line in `postgresql.conf`.
5. Restart PostgreSQL service.

That process is inconvenient when multiple databases are running on the server or admins don't have easy access to edit the `postgresql.conf` file.

### PR DESCRIPTION
**Pull request by bendiy**
I know there were recent changes to this section of the code to address the security issue of the user having permissions to execute the `start_proc` function. I do not know if this change will cause issues with those:
https://github.com/plv8/plv8/commit/57db50d0dade7a840a8f325e5d0c89ef7fc71466
https://github.com/plv8/plv8/commit/c25ba0dd6de7e08e062606007e89f7c870974027

### CODE REVIEW

**Comment by JerrySievert** [comment]
I didn't create a regression test for the security issues at the time due to the nature of the security issues, and how widespread plv8 was deployed (it was a lot of manual testing to validate the code).  now that this has been mitigated, I'll create some tests and see if this causes any issues.

**Comment by JerrySievert** [comment]
I'm waiting for tests to run on https://github.com/plv8/plv8/pull/270

once all tests pass, and I merge in, I'll let you know so you can pull from master.

this should help validate the changes.

**Comment by JerrySievert** [comment]
ok, go ahead and pull from master, should give you extra tests.

**Comment by bendiy** [comment]
@JerrySievert 
Tests pass locally after merging in your latest. The should pass travis-ci too.

```
$ make installcheck PG_CONFIG=/usr/lib/postgresql/9.5/bin/pg_config
/usr/lib/postgresql/9.5/lib/pgxs/src/makefiles/../../src/test/regress/pg_regress --inputdir=./ --bindir='/usr/lib/postgresql/9.5/bin'    --dbname=contrib_regression init-extension plv8 plv8-errors inline json startup_pre startup varparam json_conv jsonb_conv window guc es6 arraybuffer composites currentresource startup_perms dialect
(using postmaster on Unix socket, default port)
============== dropping database "contrib_regression" ==============
NOTICE:  database "contrib_regression" does not exist, skipping
DROP DATABASE
============== creating database "contrib_regression" ==============
CREATE DATABASE
ALTER DATABASE
============== running regression test queries        ==============
test init-extension           ... ok
test plv8                     ... ok
test plv8-errors              ... ok
test inline                   ... ok
test json                     ... ok
test startup_pre              ... ok
test startup                  ... ok
test varparam                 ... ok
test json_conv                ... ok
test jsonb_conv               ... ok
test window                   ... ok
test guc                      ... ok
test es6                      ... ok
test arraybuffer              ... ok
test composites               ... ok
test currentresource          ... ok
test startup_perms            ... ok
test dialect                  ... ok

======================
 All 18 tests passed.
======================

```

**Comment by JerrySievert** [comment]
great!  I'll see about getting this merged in a little bit.

**Comment by bendiy** [comment]
Thanks!
Do you have any plans to do a new tag/release soon?

**Comment by JerrySievert** [comment]
`startup` is now failing for me.

**Comment by JerrySievert** [comment]
```
*** /Users/jerry/work/plv8/expected/startup.out	2018-04-13 09:37:37.000000000 -0700
--- /Users/jerry/work/plv8/results/startup.out	2018-04-13 09:39:12.000000000 -0700
***************
*** 1,9 ****
  -- test startup failure
  set plv8.start_proc = foo;
  do $$ plv8.elog(NOTICE, 'foo = ' + foo) $$ language plv8;
! WARNING:  failed to find js function function "foo" does not exist
! ERROR:  ReferenceError: foo is not defined
! CONTEXT:  undefined() LINE 1:  plv8.elog(NOTICE, 'foo = ' + foo) 
  \c
  set plv8.start_proc = startup;
  do $$ plv8.elog(NOTICE, 'foo = ' + foo) $$ language plv8;
--- 1,7 ----
  -- test startup failure
  set plv8.start_proc = foo;
  do $$ plv8.elog(NOTICE, 'foo = ' + foo) $$ language plv8;
! ERROR:  function "foo" does not exist
  \c
  set plv8.start_proc = startup;
  do $$ plv8.elog(NOTICE, 'foo = ' + foo) $$ language plv8;

======================================================================

```

**Comment by JerrySievert** [comment]
n/m, I didn't do a `make install` before running `make installcheck`. embarrassing :)

**Comment by JerrySievert** [comment]
I'm working on cutting a release right now.

**Pull request merged**
